import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
const docs=[
 ["01","Telemeditsina roziligi","Onlayn ko‘rikning imkoniyatlari, cheklovlari va bemorning ongli roziligi."],
 ["02","Tibbiy xavflar haqida ogohlantirish","Masofaviy ko‘rik ayrim holatlarda yuzma-yuz tekshiruv o‘rnini bosa olmasligi haqida."],
 ["03","Maxfiylik va tibbiy ma’lumotlar","Qanday ma’lumot yig‘ilishi, saqlanishi va foydalanuvchi huquqlari."],
 ["04","Mustaqil doktor shartnomasi","Doktorning mustaqil maqomi, verifikatsiya, klinik javobgarlik va platforma qoidalari."],
 ["05","Bemor foydalanish qoidalari","Hisob xavfsizligi, aniq ma’lumot kiritish va platformadan foydalanish tartibi."],
 ["06","Bekor qilish va kompensatsiya siyosati","Vaqt intizomi, 5 daqiqalik kutish va tomonlar huquqlarini himoya qilish tartibi."],
];
export const metadata={title:"Huquqiy hujjatlar — ClinIQ",description:"ClinIQ platformasining huquqiy hujjatlari va foydalanuvchi huquqlari."};
export default function LegalPage(){return <div className="site-shell"><SiteHeader/><main className="legal-page"><div className="legal-hero"><span>ClinIQ huquqiy markazi</span><h1>Ishonch aniq qoidalardan boshlanadi.</h1><p>Platformadan foydalanishdan oldin huquqlaringiz, tibbiy ma’lumotlaringiz va masofaviy ko‘rik chegaralarini tushunarli tilda bilib oling.</p></div><div className="legal-notice"><b>Muhim eslatma</b><p>ClinIQ — bemor va mustaqil doktorni bog‘laydigan texnologik platforma. Tibbiy qaror va klinik javobgarlik doktor zimmasida; AI faqat yordamchi hisoblanadi.</p></div><div className="legal-doc-grid">{docs.map(x=><article key={x[0]}><span>{x[0]}</span><h2>{x[1]}</h2><p>{x[2]}</p>{x[0]==="03"?<a href="/privacy">To‘liq matn →</a>:x[0]==="05"?<a href="/terms">To‘liq matn →</a>:<small>To‘liq rasmiy matn yakuniy huquqiy tasdiqdan so‘ng e’lon qilinadi.</small>}</article>)}</div><section className="legal-principles"><h2>Asosiy tamoyillar</h2><div><p><b>Doktor mustaqil.</b> ClinIQ doktorning ish beruvchisi yoki tibbiy qaror qabul qiluvchi tomon emas.</p><p><b>AI — yordamchi.</b> AI xulosasi tashxis yoki davolash o‘rnini bosmaydi.</p><p><b>Tibbiy sir cheklangan.</b> Tizim administratorlari individual tibbiy sirlarni o‘qish huquqiga ega emas.</p><p><b>Foydalanuvchi nazorati.</b> Ma’lumotlarni ko‘rish, tuzatish va qonun doirasida o‘chirishni so‘rash mumkin.</p></div></section><div className="legal-contact"><div><small>Huquqiy yoki maxfiylik bo‘yicha savol</small><b>Biz bilan to‘g‘ridan-to‘g‘ri bog‘laning</b></div><a href="mailto:cliniq.uz@gmail.com">cliniq.uz@gmail.com</a><a href="tel:+998974646665">+998 97 464 66 65</a></div></main><SiteFooter/></div>}
