"use client";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
const APP_URL="https://cliniqpatient-production.up.railway.app";
const emergency=["Qon guruhi va rezus faktor","Allergiyalar ro‘yxati","Doimiy qabul qilinayotgan dorilar","Muhim tibbiy ma’lumotlar va surunkali kasalliklar"];
export default function LandingPage(){return <div className="site-shell"><SiteHeader home/><main>
<section id="top" className="new-hero"><div className="hero-copy reveal"><div className="eyebrow"><span/> Raqamli sog‘liq platformasi</div><h1>Kerakli shifokor.<br/><em>Sizga qulay vaqtda.</em></h1><p>Onlayn ko‘rikdan uzluksiz raqamli tibbiy tarixgacha — bemor va shifokorni bitta xavfsiz platformada birlashtiramiz.</p><div className="hero-actions"><a className="primary-action" href={`${APP_URL}/patient/login`}>Bemor sifatida kirish <span>→</span></a><a className="text-action" href="#qanday-ishlaydi">Qanday ishlaydi <span>↓</span></a></div><div className="trust-row"><span>Doktor nazorati</span><span>Yagona ClinIQ ID</span><span>Maxfiylik</span></div></div>
<div className="hero-stage" aria-label="ClinIQ raqamli tibbiy tarix vizualizatsiyasi"><div className="orb orb-one"/><div className="orb orb-two"/><div className="patient-card floating-card"><div className="mini-head"><span className="avatar">MN</span><div><b>Bemor profili</b><small>ClinIQ ID • himoyalangan</small></div><i>●</i></div><div className="health-grid"><div><small>Qon guruhi</small><strong>A (II) Rh+</strong></div><div><small>Allergiya</small><strong>Nazoratda</strong></div></div><div className="history-chart"><div className="chart-label"><span>Tibbiy tarix</span><b>Boyib boradi</b></div><svg viewBox="0 0 360 100" role="img" aria-label="Tibbiy tarix o‘sishi"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#34d6c9" stopOpacity=".48"/><stop offset="1" stopColor="#34d6c9" stopOpacity="0"/></linearGradient></defs><path d="M0 83 C45 80 55 66 92 68 S145 48 180 54 S235 29 270 36 S323 13 360 18 L360 100 L0 100Z" fill="url(#area)"/><path d="M0 83 C45 80 55 66 92 68 S145 48 180 54 S235 29 270 36 S323 13 360 18" fill="none" stroke="#25c8bb" strokeWidth="4" strokeLinecap="round"/><circle cx="360" cy="18" r="6" fill="#fff" stroke="#25c8bb" strokeWidth="4"/></svg></div></div><div className="visit-chip chip-one"><span className="pulse-dot"/><div><small>Keyingi qabul</small><b>Onlayn ko‘rik tayyor</b></div></div><div className="visit-chip chip-two"><span>AI</span><div><small>Doktor yordamchisi</small><b>Hujjatlar strukturada</b></div></div></div></section>
<section className="problem-band"><div><b>Muammo doktorlar sonida emas.</b><p>Yo‘l, navbat, ish jadvali va hududiy masofa bemorni kerakli yordamdan uzoqlashtiradi.</p></div><div className="bar-chart"><div><span>An’anaviy yo‘l</span><i className="long-bar"/><b>Yo‘l + navbat + ko‘rik</b></div><div><span>ClinIQ bilan</span><i className="short-bar"/><b>Doktor + onlayn ko‘rik</b></div></div></section>
<section id="qanday-ishlaydi" className="section-wrap"><div className="section-heading"><span>Oddiy jarayon</span><h2>Doktorgacha bo‘lgan yo‘lni qisqartiramiz</h2><p>Muammo, mutaxassislik yoki ism-familiya bo‘yicha qidiring. Qulay vaqtni tanlang va ko‘rikka tayyor bo‘ling.</p></div><div className="journey">{[["01","Mos doktorni toping","Muammo yoki mutaxassislik bo‘yicha qidiring."],["02","Vaqtni tanlang","Eng yaqin bo‘sh vaqt yoki kalendardan qulay vaqt."],["03","Ko‘rikka kiring","Boshlanishidan 5 daqiqa oldin video xona ochiladi."],["04","Xulosani oling","Doktor tasdiqlagan elektron xulosa profilingizga tushadi."]].map((x,i)=><article key={x[0]}><div className="step-top"><b>{x[0]}</b><span>{i<3?"→":"✓"}</span></div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="imkoniyatlar" className="dark-section"><div className="dark-intro"><span>Ko‘rikdan keyin ham qiymat</span><h2>Har bir ko‘rik — tibbiy tarixingizning davomidir</h2><p>Oddiy messenjer suhbatni saqlaydi. ClinIQ esa shifokor xulosasi, hujjatlar va sog‘liq tarixini tartibli, uzluksiz yozuvga aylantiradi.</p></div><div className="record-visual"><div className="record-axis"><span>1-ko‘rik</span><span>Analiz</span><span>2-ko‘rik</span><span>Doktor xulosasi</span></div><div className="record-line"><i/><i/><i/><i/></div><div className="record-outcome"><small>Yagona ClinIQ ID</small><strong>Bir bemor. Bitta uzluksiz tarix.</strong></div></div><div className="benefit-grid">{[["01","Vaqtni tejaydi","Yo‘l, navbat va klinikaga qatnash o‘rniga doktor bilan onlayn ko‘rishing."],["02","Hududdan qat’i nazar","Toshkentdagi yoki boshqa hududdagi mos mutaxassisni bir joydan toping."],["03","Hujjatlar yo‘qolmaydi","Ko‘rik xulosasi va tibbiy ma’lumotlar ClinIQ profilingizda saqlanadi."],["04","Keyingi ko‘rik oson","Yangi doktor ham avvalgi tarixni tartibli ko‘rib, jarayonni davom ettira oladi."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="ai" className="section-wrap ai-layout"><div className="ai-orbit" aria-hidden="true"><div className="ai-core">AI<small>yordamchi</small></div>{["Hujjat","Simptom","Tarix","Xulosa"].map((x,i)=><span key={x} className={`sat sat-${i+1}`}>{x}</span>)}</div><div className="section-heading left"><span>Doktor uchun AI yordamchi</span><h2>Ma’lumotni tartiblaydi. Qarorni doktor qabul qiladi.</h2><p>AI tibbiy hujjatlarni o‘qish va strukturaga keltirish, simptom va tarixdan muhim ma’lumotlarni ajratish hamda taxminiy tahlil tayyorlashda yordam beradi.</p><div className="doctor-rule"><i>✓</i><div><b>Yakuniy qaror har doim doktorniki</b><small>AI tashxis qo‘ymaydi va doktor o‘rnini egallamaydi.</small></div></div></div></section>
<section id="shaxsiy" className="personal-section"><div className="personal-copy"><span>Bepul va anonim</span><h2>Shaxsiy maslahat</h2><p>Nozik va oilaviy hayot, erkaklar va ayollar salomatligiga oid savollar uchun tushunarli javoblar. Savol-javoblar shaxssizlantiriladi.</p><a href={`${APP_URL}/patient/login`}>Savollarni ko‘rish →</a></div><div className="question-stack"><div className="q-card q-back">Maxfiy • Ismsiz • Tushunarli</div><div className="q-card q-mid">Savolingizni erkin yozing</div><div className="q-card q-front"><small>Shaxsiy maslahat</small><b>Siz so‘raysiz. Mutaxassis javob beradi.</b><span>Shaxs ko‘rsatilmaydi</span></div></div></section>
<section id="xavfsizlik" className="section-wrap emergency-layout"><div className="section-heading left"><span>Favqulodda karta</span><h2>Muhim ma’lumot — bir qarashda</h2><p>Favqulodda vaziyatda bemorning hayotiy tibbiy ma’lumotlarini tez ko‘rish uchun mo‘ljallangan karta.</p><ul>{emergency.map(x=><li key={x}><i>✓</i>{x}</li>)}</ul></div><div className="emergency-card"><div className="sos-head"><span>SOS</span><div><small>Favqulodda tibbiy karta</small><b>ClinIQ ID • 24/7</b></div></div>{emergency.map((x,i)=><div className="em-row" key={x}><span>0{i+1}</span><p>{x}</p><b>Saqlangan</b></div>)}<div className="roadmap-note"><b>Keyingi bosqich</b><span>SOS va yaqin insonga telefon yoki Telegram orqali xabar berish roadmap tarkibida.</span></div></div></section>
<section id="doktorlar" className="doctor-section"><div className="section-heading"><span>Doktorlar uchun</span><h2>Jadvalingiz sizniki. Tibbiy jarayon — tartibda.</h2></div><div className="doctor-grid">{[["01","Moslashuvchan jadval","Ish vaqti va ko‘rik davomiyligini mustaqil belgilang."],["02","Elektron ish maydoni","Bemor tarixi, hujjatlar, video ko‘rik va xulosa bitta oqimda."],["03","Raqamli reputatsiya","Masofadan bemor qabul qiling va professional profilingizni rivojlantiring."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><a className="doctor-cta" href={`${APP_URL}/doctor/login`}>Doktor kabinetiga kirish <span>→</span></a></section>
<section id="huquqiy" className="legal-strip"><div><span>Huquqiy shaffoflik</span><h2>Ma’lumotlaringiz va huquqlaringiz qanday himoyalanishini biling.</h2></div><a href="/legal">Huquqiy hujjatlarni ko‘rish <span>→</span></a></section>
<section id="aloqa" className="contact-section"><div><span>O‘zbekiston → Markaziy Osiyo</span><h2>Sog‘liq xizmatiga yo‘lni birga qisqartiramiz.</h2></div><div className="contact-links"><a href="tel:+998974646665"><small>Telefon</small><b>+998 97 464 66 65</b></a><a href="mailto:cliniq.uz@gmail.com"><small>Elektron pochta</small><b>cliniq.uz@gmail.com</b></a></div></section>
</main><SiteFooter/></div>}
