"use client";
import {useEffect} from "react";
import {useSiteLanguage as useLang} from "@/lib/site-language";

type Pair={ru:string;en:string};
const COPY:Record<string,Pair>={
"Qanday ishlaydi":{ru:"Как это работает",en:"How it works"},"Imkoniyatlar":{ru:"Возможности",en:"Features"},"AI yordamchi":{ru:"ИИ-помощник",en:"AI assistant"},"Doktorlar":{ru:"Врачи",en:"Doctors"},"Huquqiy hujjatlar":{ru:"Правовые документы",en:"Legal documents"},"Kirish":{ru:"Войти",en:"Sign in"},
"Raqamli sog‘liq platformasi":{ru:"Цифровая платформа здоровья",en:"Digital health platform"},"Kerakli shifokor.":{ru:"Нужный врач.",en:"The right doctor."},"Sizga qulay vaqtda.":{ru:"В удобное для вас время.",en:"At a time that works for you."},"Onlayn ko‘rikdan uzluksiz raqamli tibbiy tarixgacha — bemor va shifokorni bitta xavfsiz platformada birlashtiramiz.":{ru:"От онлайн-приёма до непрерывной цифровой истории здоровья — объединяем пациента и врача на одной защищённой платформе.",en:"From online visits to a continuous digital health record — bringing patients and doctors together on one secure platform."},"Bemor sifatida kirish":{ru:"Войти как пациент",en:"Continue as a patient"},"Doktor nazorati":{ru:"Контроль врача",en:"Clinician oversight"},"Yagona ClinIQ ID":{ru:"Единый ClinIQ ID",en:"One ClinIQ ID"},"Maxfiylik":{ru:"Конфиденциальность",en:"Privacy"},
"Bemor profili":{ru:"Профиль пациента",en:"Patient profile"},"ClinIQ ID • himoyalangan":{ru:"ClinIQ ID • защищено",en:"ClinIQ ID • protected"},"Qon guruhi":{ru:"Группа крови",en:"Blood group"},"Allergiya":{ru:"Аллергия",en:"Allergy"},"Nazoratda":{ru:"Под контролем",en:"Monitored"},"Tibbiy tarix":{ru:"История здоровья",en:"Health record"},"Boyib boradi":{ru:"Дополняется",en:"Keeps growing"},"Keyingi qabul":{ru:"Следующий приём",en:"Next visit"},"Onlayn ko‘rik tayyor":{ru:"Онлайн-приём готов",en:"Online visit ready"},"Doktor yordamchisi":{ru:"Помощник врача",en:"Doctor assistant"},"Hujjatlar strukturada":{ru:"Документы структурированы",en:"Documents structured"},
"Muammo doktorlar sonida emas.":{ru:"Проблема не в количестве врачей.",en:"The problem is not the number of doctors."},"Yo‘l, navbat, ish jadvali va hududiy masofa bemorni kerakli yordamdan uzoqlashtiradi.":{ru:"Дорога, очереди, рабочий график и расстояние затрудняют доступ к нужной помощи.",en:"Travel, queues, work schedules and distance keep patients from the care they need."},"An’anaviy yo‘l":{ru:"Обычный путь",en:"Traditional path"},"Yo‘l + navbat + ko‘rik":{ru:"Дорога + очередь + приём",en:"Travel + queue + visit"},"ClinIQ bilan":{ru:"С ClinIQ",en:"With ClinIQ"},"Doktor + onlayn ko‘rik":{ru:"Врач + онлайн-приём",en:"Doctor + online visit"},
"Oddiy jarayon":{ru:"Простой процесс",en:"A simple process"},"Doktorgacha bo‘lgan yo‘lni qisqartiramiz":{ru:"Сокращаем путь к врачу",en:"A shorter path to your doctor"},"Muammo, mutaxassislik yoki ism-familiya bo‘yicha qidiring. Qulay vaqtni tanlang va ko‘rikka tayyor bo‘ling.":{ru:"Ищите по проблеме, специальности или имени. Выберите удобное время и подготовьтесь к приёму.",en:"Search by concern, specialty or name. Choose a convenient time and get ready for your visit."},"Mos doktorni toping":{ru:"Найдите подходящего врача",en:"Find the right doctor"},"Muammo yoki mutaxassislik bo‘yicha qidiring.":{ru:"Ищите по проблеме или специальности.",en:"Search by concern or specialty."},"Vaqtni tanlang":{ru:"Выберите время",en:"Choose a time"},"Eng yaqin bo‘sh vaqt yoki kalendardan qulay vaqt.":{ru:"Ближайшее свободное или удобное время в календаре.",en:"Pick the nearest opening or a time from the calendar."},"Ko‘rikka kiring":{ru:"Подключитесь к приёму",en:"Join the visit"},"Boshlanishidan 5 daqiqa oldin video xona ochiladi.":{ru:"Видеокомната откроется за 5 минут до начала.",en:"The video room opens 5 minutes before the visit."},"Xulosani oling":{ru:"Получите заключение",en:"Receive the conclusion"},"Doktor tasdiqlagan elektron xulosa profilingizga tushadi.":{ru:"Подтверждённое врачом заключение появится в вашем профиле.",en:"The doctor-approved electronic conclusion appears in your profile."},
"Ko‘rikdan keyin ham qiymat":{ru:"Ценность после приёма",en:"Value beyond the visit"},"Har bir ko‘rik — tibbiy tarixingizning davomidir":{ru:"Каждый приём продолжает вашу историю здоровья",en:"Every visit continues your health story"},"Oddiy messenjer suhbatni saqlaydi. ClinIQ esa shifokor xulosasi, hujjatlar va sog‘liq tarixini tartibli, uzluksiz yozuvga aylantiradi.":{ru:"Обычный мессенджер хранит переписку. ClinIQ превращает заключения, документы и данные здоровья в упорядоченную непрерывную историю.",en:"A messenger saves a chat. ClinIQ turns conclusions, documents and health data into one organized, continuous record."},"Bir bemor. Bitta uzluksiz tarix.":{ru:"Один пациент. Одна непрерывная история.",en:"One patient. One continuous record."},
"Vaqtni tejaydi":{ru:"Экономит время",en:"Saves time"},"Hududdan qat’i nazar":{ru:"Независимо от региона",en:"Care across regions"},"Hujjatlar yo‘qolmaydi":{ru:"Документы не теряются",en:"Documents stay with you"},"Keyingi ko‘rik oson":{ru:"Проще продолжить лечение",en:"Easier follow-up"},
"Doktor uchun AI yordamchi":{ru:"ИИ-помощник для врача",en:"AI assistant for doctors"},"Ma’lumotni tartiblaydi. Qarorni doktor qabul qiladi.":{ru:"Структурирует данные. Решение принимает врач.",en:"It organizes information. The doctor decides."},"Yakuniy qaror har doim doktorniki":{ru:"Окончательное решение всегда за врачом",en:"The final decision always belongs to the doctor"},"AI tashxis qo‘ymaydi va doktor o‘rnini egallamaydi.":{ru:"ИИ не ставит диагноз и не заменяет врача.",en:"AI does not diagnose or replace the doctor."},
"Bepul va anonim":{ru:"Бесплатно и анонимно",en:"Free and anonymous"},"Shaxsiy maslahat":{ru:"Личный совет",en:"Private guidance"},"Savollarni ko‘rish":{ru:"Посмотреть вопросы",en:"View questions"},"Siz so‘raysiz. Mutaxassis javob beradi.":{ru:"Вы спрашиваете. Специалист отвечает.",en:"You ask. A specialist answers."},"Shaxs ko‘rsatilmaydi":{ru:"Личность не раскрывается",en:"Identity remains private"},
"Favqulodda karta":{ru:"Экстренная карта",en:"Emergency card"},"Muhim ma’lumot — bir qarashda":{ru:"Важные данные — с первого взгляда",en:"Critical information at a glance"},"Favqulodda tibbiy karta":{ru:"Экстренная медицинская карта",en:"Emergency medical card"},"Saqlangan":{ru:"Сохранено",en:"Saved"},"Keyingi bosqich":{ru:"Следующий этап",en:"Next phase"},
"Doktorlar uchun":{ru:"Для врачей",en:"For doctors"},"Jadvalingiz sizniki. Tibbiy jarayon — tartibda.":{ru:"Ваш график — ваш выбор. Клинический процесс — в порядке.",en:"Your schedule, your choice. The care process, organized."},"Moslashuvchan jadval":{ru:"Гибкий график",en:"Flexible schedule"},"Elektron ish maydoni":{ru:"Цифровое рабочее пространство",en:"Digital workspace"},"Raqamli reputatsiya":{ru:"Цифровая репутация",en:"Digital reputation"},"Doktor kabinetiga kirish":{ru:"Войти в кабинет врача",en:"Enter doctor workspace"},
"Huquqiy shaffoflik":{ru:"Правовая прозрачность",en:"Legal transparency"},"Ma’lumotlaringiz va huquqlaringiz qanday himoyalanishini biling.":{ru:"Узнайте, как защищаются ваши данные и права.",en:"Know how your data and rights are protected."},"Huquqiy hujjatlarni ko‘rish":{ru:"Открыть правовые документы",en:"View legal documents"},"Sog‘liq xizmatiga yo‘lni birga qisqartiramiz.":{ru:"Вместе делаем путь к медицинской помощи короче.",en:"Together, we shorten the path to care."},"Telefon":{ru:"Телефон",en:"Phone"},"Elektron pochta":{ru:"Электронная почта",en:"Email"},"Platforma":{ru:"Платформа",en:"Platform"},"Huquqiy":{ru:"Правовая информация",en:"Legal"},"Bog‘lanish":{ru:"Контакты",en:"Contact"},"Barcha hujjatlar":{ru:"Все документы",en:"All documents"},"Maxfiylik siyosati":{ru:"Политика конфиденциальности",en:"Privacy policy"},"Foydalanish shartlari":{ru:"Условия использования",en:"Terms of use"},"Barcha huquqlar himoyalangan.":{ru:"Все права защищены.",en:"All rights reserved."}
,
"1-ko‘rik":{ru:"1-й приём",en:"Visit 1"},"Analiz":{ru:"Анализы",en:"Lab test"},"2-ko‘rik":{ru:"2-й приём",en:"Visit 2"},"Doktor xulosasi":{ru:"Заключение врача",en:"Doctor's conclusion"},
"Yo‘l, navbat va klinikaga qatnash o‘rniga doktor bilan onlayn ko‘rishing.":{ru:"Вместо дороги, очередей и поездок в клинику проконсультируйтесь с врачом онлайн.",en:"See a doctor online instead of travelling to and waiting at a clinic."},"Toshkentdagi yoki boshqa hududdagi mos mutaxassisni bir joydan toping.":{ru:"Найдите подходящего специалиста из Ташкента или другого региона в одном месте.",en:"Find the right specialist in Tashkent or another region, all in one place."},"Ko‘rik xulosasi va tibbiy ma’lumotlar ClinIQ profilingizda saqlanadi.":{ru:"Заключения и медицинские данные сохраняются в вашем профиле ClinIQ.",en:"Visit conclusions and medical information stay in your ClinIQ profile."},"Yangi doktor ham avvalgi tarixni tartibli ko‘rib, jarayonni davom ettira oladi.":{ru:"Новый врач сможет изучить упорядоченную историю и продолжить лечение.",en:"A new doctor can review your organized history and continue your care."},
"AI tibbiy hujjatlarni o‘qish va strukturaga keltirish, simptom va tarixdan muhim ma’lumotlarni ajratish hamda taxminiy tahlil tayyorlashda yordam beradi.":{ru:"ИИ помогает читать и структурировать медицинские документы, выделять важные сведения из симптомов и анамнеза и готовить предварительный анализ.",en:"AI helps read and structure medical documents, extract key information from symptoms and history, and prepare a preliminary analysis."},"yordamchi":{ru:"помощник",en:"assistant"},"Hujjat":{ru:"Документ",en:"Document"},"Simptom":{ru:"Симптом",en:"Symptom"},"Tarix":{ru:"История",en:"History"},"Xulosa":{ru:"Заключение",en:"Conclusion"},
"Nozik va oilaviy hayot, erkaklar va ayollar salomatligiga oid savollar uchun tushunarli javoblar. Savol-javoblar shaxssizlantiriladi.":{ru:"Понятные ответы на деликатные вопросы о семейной жизни, мужском и женском здоровье. Вопросы и ответы обезличиваются.",en:"Clear answers to sensitive questions about family life and men's and women's health. Questions and answers are anonymized."},"Maxfiy • Ismsiz • Tushunarli":{ru:"Конфиденциально • Анонимно • Понятно",en:"Private • Anonymous • Clear"},"Savolingizni erkin yozing":{ru:"Задайте свой вопрос свободно",en:"Ask your question freely"},
"Favqulodda vaziyatda bemorning hayotiy tibbiy ma’lumotlarini tez ko‘rish uchun mo‘ljallangan karta.":{ru:"Карта для быстрого просмотра жизненно важных медицинских данных пациента в экстренной ситуации.",en:"A card designed for quick access to a patient's vital medical information in an emergency."},"Qon guruhi va rezus faktor":{ru:"Группа крови и резус-фактор",en:"Blood group and Rh factor"},"Allergiyalar ro‘yxati":{ru:"Список аллергий",en:"Allergy list"},"Doimiy qabul qilinayotgan dorilar":{ru:"Постоянно принимаемые лекарства",en:"Regular medications"},"Muhim tibbiy ma’lumotlar va surunkali kasalliklar":{ru:"Важные медицинские данные и хронические заболевания",en:"Important medical information and chronic conditions"},"SOS va yaqin insonga telefon yoki Telegram orqali xabar berish roadmap tarkibida.":{ru:"Уведомления SOS и близкому человеку по телефону или через Telegram входят в дорожную карту.",en:"SOS alerts and notifications to a trusted contact by phone or Telegram are on the roadmap."},
"Ish vaqti va ko‘rik davomiyligini mustaqil belgilang.":{ru:"Самостоятельно задавайте рабочее время и длительность приёма.",en:"Set your own working hours and appointment duration."},"Bemor tarixi, hujjatlar, video ko‘rik va xulosa bitta oqimda.":{ru:"История пациента, документы, видеоприём и заключение — в одном процессе.",en:"Patient history, documents, video visits, and conclusions in one workflow."},"Masofadan bemor qabul qiling va professional profilingizni rivojlantiring.":{ru:"Принимайте пациентов дистанционно и развивайте профессиональный профиль.",en:"See patients remotely and grow your professional profile."},
"O‘zbekiston → Markaziy Osiyo":{ru:"Узбекистан → Центральная Азия",en:"Uzbekistan → Central Asia"},"Onlayn ko‘rikdan boshlanadigan raqamli sog‘liq platformasi.":{ru:"Цифровая платформа здоровья, начинающаяся с онлайн-приёма.",en:"A digital health platform that starts with an online visit."},"Toshkent, O‘zbekiston":{ru:"Ташкент, Узбекистан",en:"Tashkent, Uzbekistan"},"Savollarni ko‘rish →":{ru:"Посмотреть вопросы →",en:"View questions →"},"Digital health":{ru:"Цифровое здоровье",en:"Digital health"},"Light":{ru:"Светлая",en:"Light"}
};
const originals=new WeakMap<Text,string>();
function cyr(s:string){return s.replace(/Sh/g,"Ш").replace(/sh/g,"ш").replace(/Ch/g,"Ч").replace(/ch/g,"ч").replace(/Yo/g,"Ё").replace(/yo/g,"ё").replace(/Yu/g,"Ю").replace(/yu/g,"ю").replace(/Ya/g,"Я").replace(/ya/g,"я").replace(/O‘|O'/g,"Ў").replace(/o‘|o'/g,"ў").replace(/G‘|G'/g,"Ғ").replace(/g‘|g'/g,"ғ").replace(/[A-Za-z]/g,x=>({a:"а",b:"б",d:"д",e:"е",f:"ф",g:"г",h:"ҳ",i:"и",j:"ж",k:"к",l:"л",m:"м",n:"н",o:"о",p:"п",q:"қ",r:"р",s:"с",t:"т",u:"у",v:"в",x:"х",y:"й",z:"з",A:"А",B:"Б",D:"Д",E:"Е",F:"Ф",G:"Г",H:"Ҳ",I:"И",J:"Ж",K:"К",L:"Л",M:"М",N:"Н",O:"О",P:"П",Q:"Қ",R:"Р",S:"С",T:"Т",U:"У",V:"В",X:"Х",Y:"Й",Z:"З"} as Record<string,string>)[x]||x)}
export default function SiteLanguageSync(){const{lang}=useLang();useEffect(()=>{document.documentElement.lang=lang==="ru"?"ru":lang==="en"?"en":"uz";const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n:Node|null;while(n=w.nextNode()){const t=n as Text;if(!t.nodeValue?.trim()||["SCRIPT","STYLE"].includes(t.parentElement?.tagName||"")||t.parentElement?.closest(".language-control,.new-language-menu"))continue;const base=originals.get(t)||t.nodeValue;originals.set(t,base);const clean=base.trim();const lead=base.match(/^\s*/)?.[0]||"",trail=base.match(/\s*$/)?.[0]||"";if(lang==="uz")t.nodeValue=base;else if(lang==="uzc")t.nodeValue=lead+cyr(clean)+trail;else{const v=COPY[clean]?.[lang];t.nodeValue=v?lead+v+trail:base}}},[lang]);return null}
